### ISSUE TITLE
Silent Authentication On Page Load / Public Route Issue

### ISSUE THREAD

**Issue by coolhome** [perarnborg/vuex-oidc#121]
When `silentRedirectUri` is set, it is not considered a public route. On page load it will attempt to authenticate silent BUT the router middleware will intercept the silent renew callback and force a redirect authentication in the middle of a silent authenticate.

Resulting in two/three authorize calls by the end of the first completed login. Both a silent renew AND redirect authentication occurs.

PR #122 will add the `silentRedirectUri` to the public routes so on first page load it can attempt a silent authentication.

**Comment by ux-engineer** [comment]
I've implemented a different kind of use case with this library, of not using vuexOidcCreateRouterMiddleware() and not creating a view for OidcCallback route, but rather using redirects in auth guard level.

With this approach I can have all the auth flow logic in two files src/router/auth/guard.ts and src/router/auth/listeners.ts instead of having to jump between files to grasp how the flow goes...

And more importantly, this allows me to use async component loader, so that I can have an global level page loading indicator shown while the router ends up to loading a view.

I could make an example repo out of this if there is interest... This also probably is needing some further development soon, when we are upgrading to Vue 3.0.

Yesterday I was debugging the router redirects and noticed seemingly unnecessary hops... This issue here could explain some of it.

**Comment by perarnborg** [comment]
Thanks @coolhome your PR is published in v3.9.1.

@ux-engineer If you put together an example rep I can link to it from the docs!

**Comment by rainergp** [comment]
@ux-engineer by any chance did you implement that example? It might be very helpful for me. Thanks!
