### ISSUE TITLE
How to get working with vue cli 3?

### ISSUE THREAD

**Issue by tommed** [perarnborg/vuex-oidc#14]
I've noticed the example uses webpack and separates the silent renewal from the main SPA.

Is there anyway to get silent renew working inside the one SPA? I've tried with the routing flags:

### router.js

```javascript
//...
{
      path: '/silent-refresh-oidc',
      name: 'silent-refresh-oidc',
      component: OidcSilentRefresh,
      meta: {
        isOidcCallback: true,
        isPublic: true,
      },
    },
//...
```

### OidcSilentRefresh.vue

```html
<template>
  <div></div>
</template>

<script>
import { vuexOidcProcessSilentSignInCallback } from 'vuex-oidc';
import OidcSettings from '../oidc-config';

export default {
  mounted() {
    vuexOidcProcessSilentSignInCallback(OidcSettings);
  },
};
</script>

```

But the access token never seems to get updated. I will produce a simple reproducable example repo and post a link to it in this ticket to show the silent renewal working, but failing to update the ticket, which causes a high number of requests to the auth server, but then the user loosing their access token.

No errors on console that I can see.

**Comment by tommed** [comment]
https://github.com/VigilantApps/vuexoidc-silent-renewal-example

**Comment by perarnborg** [comment]
@tommed I see why you would want to do this, but I also think that it could be hard to acheive (and possibly not even desirable). Since the request to the silent renew callback will be made in an iframe the whole vue app would load inside the iframe, including creation of the vuex store. When the vuex store is created in the app instance in the iframe an oidc user manager will be created and I think this will be error prone, since what the silent renewal callback is supposed to do is to also create oidc user manager and process the callback with it.

If you do not want to split up your vue cli app with multiple entry points an alternative is to let the silent renewal callback be a completely static html file that loads a completely static js file. If this is something that you think would be nicer I can start shipping a UMD version of vuex-oidc that you can use directly in the browser...

**Comment by tommed** [comment]
Thanks @perarnborg. I'm not precious about the silent file being part of the SPA at all, although I'm not sure I understand the flow from this page enough to understand how it would pass the access token back to the parent page in order for vuex to complete.

In the situation you described, would the static page simply refer to its own copy of oidc-client.js and simple finish the callback itself? If so, which parts of the user manager configuration need to be supplied?

**Comment by tommed** [comment]
This branch shows the use of a static file, but it appears to still result in a redirect loop?

https://github.com/VigilantApps/vuexoidc-silent-renewal-example/tree/alternative/static_silent_page

**Comment by perarnborg** [comment]
At first glance I think the problem can be that you are calling the UserManager constructor without any settings, like authority and client id (https://github.com/IdentityModel/oidc-client-js/wiki#configuration).

You can fond these settings in you oidc config (https://github.com/VigilantApps/vuexoidc-silent-renewal-example/blob/alternative/static_silent_page/src/oidc-config.js).

**Comment by tommed** [comment]
This was in-line with the oidc-client examples (which use `new UserManager().signinSilentCallback()`) and according to [the code](https://github.com/IdentityModel/oidc-client-js/blob/dcc644096f8de79a58372b4c88c987d53184163f/src/UserManager.js#L184), it doesn't appear to use the config for this part anyway?

Regardless, I added in `authority, client_id, response_type` and `scope` but found it produced the same issue.

**Comment by perarnborg** [comment]
OK, got it! I'll try to take a look at the code sample within short!

**Comment by perarnborg** [comment]
@tommed I did not get this problem myself when I tried with my open id authority. Are you sure you have whitelisted all of the redirect uris? If for instance you are using Google as authority you need to whitelist both redirect_uri (http://localhost:8080/signin-oidc) and silent_redirect_uri (http://localhost:8080/silent-refresh-oidc.html) under Authorized redirect URIs.

**Comment by tommed** [comment]
Yeh, we're not getting any errors on the side of the authorisation server, and both URLs are whitelisted. If this is a workable concept, I'll get the guys here to re-test and see why we're getting a redirect loop. Another option is to give you temp user and client access to our auth server if we're confident this isn't on our side... but it sounds like someone missed something somewhere... thanks for your time, we'll look at this over the next 2 days and confirm.

**Comment by tommed** [comment]
IMHO the most elegant developer experience would be to get the silent renewal a part of the existing SPA router if this is possible - just as you do for the `signin-oidc` callback.

**Comment by perarnborg** [comment]
I can agree with you that it would be more simple for developers to implement the silent renew in vuex-oidc if it is possible to incorporate the silent renew callback in a vue route. When I have built open id client apps in the past I have gone for the approach of having a static file for the callback since it keeps the callback as simple as possible, but I will give this some thought.

However I believe the issue that you are seeing is not an effect of vuex-oidc not supporting the concept of a separate static file in public – because it should. 

Even though the actual callback is outside of the vuex app, what happens is that the auth request and redirect back to your silent_redirect_uri all happens in an iframe, and that iframe notifies the parent window of the authentication result. The parent window resolves a promise (this is in UserManage.signinSilent). All of this is happening inside oidc-client, and that promise is what the vuex module listens for.

The error you are seeing is actually being thrown inside of oidc-client (storage refers to the storage that oidc-client uses internally to make sure the callback is actually the user it says it is) and this is an error you should be getting if either that storage is missing for some reason or if the url hash of the callback url does not contain what oidc-client expects it to.

It is quite hard to explain this, I hope you can follow.

I did however make some improvements of the silent authentication handling (in v1.10.5), you can try to update vuex-oidc and see if you still have problems. If you do I would gladly take a look (allthough not in the next couple of days) if you give me access to you open id authority (temporarily of course) and provide the details needed.

**Comment by perarnborg** [comment]
(This is what I believe is the issue, that being said I am not 100% certain)

**Comment by perarnborg** [comment]
@tommed OK, so I managed to reproduce the issue when using your login server. As far as I can see the problem is not in the vuex-oidc implementation, since the authorization request for the silent renew looks correct and the redirect loop looks like it is created in the dependency oidc-client.

My prime suspect is related to the cookie policy in the .net identity server (login.vigilantapps.com is running .net, right?). See the following two issues and the suggestions for fixes in them:

https://github.com/IdentityModel/oidc-client-js/issues/651
https://github.com/IdentityModel/oidc-client-js/issues/663

What do you think about this? Have you had a client authenticating with implicit flow before against your authority?

I might be able to spend some more time debugging this, but this is as far as I have gotten now.

**Comment by tommed** [comment]
Per you're a gent! Yes it's a .net identity server and I've asked our guys here to test the fixes you've linked to. Appreciate you looking at this especially, as you say, if it has nothing to do with your part!

Feels like we have another member of the Vigilant team with us today 😆! 
I'll update this thread in a couple of hours once we've tried both fixes in staging.
Thanks again.

**Comment by tommed** [comment]
Strangely, if I use `oidc-client` directly from the `public` folder of a vuecli3 project, it works fine against this server 💭 so when bypassing vue's lifecycle/pipeline this works fine?!?!? 😱

**Comment by perarnborg** [comment]
OK, that’s interesting! 

Did you use the unminified code in oidc-client? One of the issues I referred to stated that they only see this when using the minified oidc-client...

I’ll have a look and see if I can find anything!

**Comment by perarnborg** [comment]
I had another look at this and cannot manage to get oidc-client working with silent renew against your authority. In this fork of oidc-client I adapted the VanillaJS UserManager sample to run against your login server (authority and client are blacked out): https://github.com/perarnborg/oidc-client-js

And I get the same problem, that oidc-client cannot get the user from its storage which triggers looping calls to to the silent renew.

If you want to try it yourself you can clone the fork and enter authority and client in /samples/VanillaJS/public/user-manager-sample-popup-signin.js

and then do `node server.js` inside of the VanillaJS directory.

Have you considered to look into any of the changes in the identity servers code/configuration that were suggested in the closed issues in oidc-client that I referenced earlier?

**Comment by tommed** [comment]
Thanks Per and apologies, I've been away for a couple of weeks. I left this with our Auth guy and he believes the reason this wasn't working (after help with the links you provided) was because they'd set the HTTP ONLY flag on the auth cookie and therefore the JScript for sharing this token was not able to access the cookie.

I'm working on attesting this with an update version of our Auth system to see if this resolves the problems. Will post as soon as I've finished.

**Comment by perarnborg** [comment]
Cool, sounds like a very plausible explanation. Looking forward to hear from you!

**Comment by tommed** [comment]
@perarnborg good news, all sorted! The security system used HTTP Only cookies to protect them from being stolen by a rogue JScript - however the implementation in `oidc-client` uses JScript to grab and share the token, this was failing and causing the loop. When implementing a prototype vuejs oidc plug-in from scratch, this issue didn't exist (as it did with your vanilla adaptation), this is because the cookie handling in `oidc-client` is an implementation detail rather than a prototype requirement.

Phew! :) thank you once again for your assistance in this! :+1:
