### ISSUE TITLE
how I can validate user by role

### ISSUE THREAD

**Issue by alexlvovich** [perarnborg/vuex-oidc#16]
I have 2 apis one for admin roles. My question is how can I check user roles on application level.

**Comment by perarnborg** [comment]
Are you saying that the admin roles are not stored on the users in the open id authority?

I do not think that this should be any concern of vuex-oidc, but something you should solve in your applications code.

**Comment by alexlvovich** [comment]
Roles are part of .NET Core Identity and part of the claims IS4 provides. Of course, I'm checking roles up on logging in, but it would be nice to have option to check proper role on callback to client as well.

**Comment by perarnborg** [comment]
If you provide the roles Claim as a custom scope in the authorization you should have the roles in the store on the user I believe?

**Comment by perarnborg** [comment]
I realized that I have limited the claims available on the oidcUser to only include the profile. I will do a rewrite that lets you check all of the claims you have scoped through a vuex getter.

Coming soon...

**Comment by perarnborg** [comment]
@alexlvovich is this something you are still looking at?

**Comment by glennvdv** [comment]
I'm looking for something similar. Currently this is what i have done:
- user-info endpoint returns the roles of the user.
- roles from user are available on User.profile object
- I created a custom authorizationStore, where i store the users roles on the userLoadedEvent

Now i'm looking to configure the oidc route middleware,so that it checks to roles aswel. Through the use of the meta data.
Do i have to write a custom route guard? Or can i extend your somehow?

**Comment by aessig** [comment]
@glennvdv Very interested in your approach, any chance you have finalised your solution by now?
