### ISSUE TITLE
Wiki update

### ISSUE THREAD

**Issue by tepsukka** [perarnborg/vuex-oidc#172]
Hi, 

As there's no way to make a pull request for wikis that I know of, I've forked over the wiki and made some small fixes to it. You can view my changes here: [https://github.com/tepsukka/vuex-oidc-wiki](https://github.com/tepsukka/vuex-oidc-wiki).

I mostly removed some extra whitespace and line breaks. Changed to `vue` syntax on a couple of code blocks,removed one extra `<script>` tag and fixed one comment. 

Maybe it would be better to copy over the wiki to the README file so that we can open up pull requests and help keep the documentation clean and up to date easier?

Thanks for your work on this project by the way, it's great!

**Comment by perarnborg** [comment]
Thank you for your positive feedback, and for contributing to improve the documentation!

I agree that it would be good to make it easy for the community to contribute to the docs. Let me think on that. 

Your changes look great, they are applied to the wiki. I also changed the heading structure slightly since you pointed out that API was an additional top level heading. :)
