### ISSUE TITLE
OIDC.Log.Logger

### ISSUE THREAD

**Issue by atlcodecommandr** [perarnborg/vuex-oidc#41]
How can I get Logging working with vuex-oidc?

**Comment by GordonBlahut** [comment]
I had to import OIDC from "vuex-oidc/node_modules/oidc-client" instead of from "oidc-client" to get the same reference used by vuex-oidc. I'm not sure why.

**Comment by perarnborg** [comment]
Sorry for not replying to this sooner. @GordonBlahut’s suggestion is how you need to do it for now. I am planning to improve the api of vuex-oidc to use the Logger of oidc-client in a for intuitive way. Will not be able to look at it until the middle of july though.

**Comment by GordonBlahut** [comment]
Is there a reason it works like that with the locked version and can't use the root level oidc-client as a peer dependency?

**Comment by perarnborg** [comment]
My reasoning when deciding to have oidc-client as a dependency rather than a peer dependency was that I was a bit scared to rely on peer dependency warnings to get a correct version of Oidc-client, and also that I did not anticipate anyone to want to interact with oidc-client outside of vuex-oidc (using the oidc logger is of course a perfect example of that).

After thinking again about this I think it was the wrong decision, and in a future update oidc-client will probably be a peer dependency as you suggest @GordonBlahut

**Comment by GordonBlahut** [comment]
@perarnborg Cool that sounds good. I was confused at first because the first line of the wiki says that oidc-client is a peer dependency.

**Comment by perarnborg** [comment]
Ouch, that’s my bad. I’ll change that, until it is a peer dep for real.

**Comment by perarnborg** [comment]
@atlcodecommandr @GordonBlahut As of v3.0.0 oidc-client is a peer dependency of vuex-oidc, rather than a locked dependency as before.

This means you need to install oidc-client separatly (as now specified in the docs), and you can use the logger of oidc-client like the oidc-client docs say:

```
import Oidc from 'oidc-client'

Oidc.Log.logger = console
```

Thank you for helping out!

**Comment by ux-engineer** [comment]
This syntax may also be used:

```js
import { Log } from 'oidc-client';

Log.logger = console;
Log.level = Log.DEBUG;
```
