### ISSUE TITLE
Possible to use hash mode routing?

### ISSUE THREAD

**Issue by jordyvaneijk** [perarnborg/vuex-oidc#48]
Hi all, 

In the example i see that the router is using history mode is it also possible to use hash mode? At the moment when I login to my IDP i get redirected back to the callback url and if i push the redirectPath like the example below

```
created() {
            this.oidcSignInCallback()
                .then((redirectPath) => {
                    console.log(redirectPath);
                    this.$router.push(redirectPath)
                })
                .catch((err) => {
                    console.error(err);
                    this.$router.push('/oidc-callback-error'); // Handle errors any way you want
                })
        }
```
I get something like `https://mydomain.com/app/#/#/`
the value in my `redirectPath` = `/#/` at this time.

If i navigate to `https://mydomain.com/app/#/oidc-test` the `redirectPath` will be `/oidc-test#/oidc-test` can this be fixed or do i need to set anything else?

**Comment by jordyvaneijk** [comment]
No one that can comment on this issue?

**Comment by perarnborg** [comment]
The package should work with hash routes, I will investigate this within the next few days.

**Comment by perarnborg** [comment]
@jordyvaneijk OK, so after thinking about this some more, I think it would be somewhat problematic to support vue-router in hash mode. The main reason is because with Open ID the response parameters are sent in the URL fragment. See [Open ID docs](https://openid.net/specs/openid-connect-core-1_0.html), chapter 3.2.2.5.  Successful Authentication Response.

So what I think you could do if you want to use hash mode is that you in stead of having a vue route as your oidc callback, you can implement a static html page that handles the callback in stead. If you want I can help you out with an example.

**Comment by jordyvaneijk** [comment]
@perarnborg an example of how to fix it would be nice.

**Comment by perarnborg** [comment]
@jordyvaneijk There is an [example](https://github.com/perarnborg/vuex-oidc-example/tree/example/hash-mode) now with hash mode.

You can see the specifics on how to go about in the [diff page on GitHub](https://github.com/perarnborg/vuex-oidc-example/compare/example/hash-mode). The idea is to have a static html page outside of the vue app that handles the callback.

You need to upgrade vuex-oidc to the latest version (v3.1.0) for this to work. Also please note that as of v3 oidc-client is a peer dependency, and you need to start to install it manually for vuex-oidc to work.

**Comment by jordyvaneijk** [comment]
Thank you so much for the quick response and creating a fix!
