### ISSUE TITLE
OidcCallback view as a route guard?

### ISSUE THREAD

**Issue by ux-engineer** [perarnborg/vuex-oidc#77]
What is the reason for implementing OidcCallback as a route view instead of a route guard?

Having a view obviously gives the benefit of showing a loading indicator. However, at least in our usage implementation of your package, we are just dispatching a oidcSignInCallback store action from that component and the browser and then redirecting page to redirectPath. User is on shown that component only so briefly that a loading indicator would just flash quickly (if no network latencies involved), or catching error and redirecting to an error page.

Is this route is for handling logic and redirecting, would a route guard be a more suitable?

**Comment by perarnborg** [comment]
You could implement the callback in a route guard if you want. I think the main reason why I prefer a route is that you typically white list a redirect uri on the provider side, and it makes sense to me that this uri matches exactly one route.

**Comment by ux-engineer** [comment]
You can still have a route defined, and use it's beforeEnter route guard?

**Comment by ux-engineer** [comment]
Btw with such a implementation using Vuex from within router, there came ESLint errors for cyclical dependency found... Circumvented by requiring store within the callback function.

**Comment by perarnborg** [comment]
I would say that this is only a matter of taste and I don't see any problem with using a route guard rather than a component. Using a component gives you the option to show something to the user while the callback is handled, but just like you point out this happens quickly in a typical scenario. However a spinner could perhaps be useful if there are network issues or problems with the provider.

Where did you say the cyclical dependency warnings were thrown?

**Comment by ux-engineer** [comment]
Yes...we are probably implementing a global loading view, as that would be useful with lazy loaded route chunks as well. However there might be some timing or scope-accessability issues with route guards, or not.

ESLint kept throwing em...we are using TypeScript with Vue CLI eslint presets and ESLint's VS Code extension.
